# Shell variables
# Generated by 'wal'
wallpaper='/home/baphomet/Pictures/wallpaper16.jpg'

# Special
background='#131c1c'
foreground='#d6dad6'
cursor='#d6dad6'

# Colors
color0='#131c1c'
color1='#75AFAF'
color2='#8EB9B7'
color3='#ACB3AB'
color4='#D79588'
color5='#D0AA9D'
color6='#B7C3BB'
color7='#d6dad6'
color8='#959895'
color9='#75AFAF'
color10='#8EB9B7'
color11='#ACB3AB'
color12='#D79588'
color13='#D0AA9D'
color14='#B7C3BB'
color15='#d6dad6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
