--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/baphomet/Pictures/wallpaper15.jpg"

-- Special
background="#090914"
foreground="#cca8a5"
cursor="#cca8a5"

-- Colors
color0="#090914"
color1="#6F3441"
color2="#673D47"
color3="#953343"
color4="#944644"
color5="#AB4D47"
color6="#BF4047"
color7="#cca8a5"
color8="#8e7573"
color9="#6F3441"
color10="#673D47"
color11="#953343"
color12="#944644"
color13="#AB4D47"
color14="#BF4047"
color15="#cca8a5"
