--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/baphomet/Pictures/wallpaper.jpg"

-- Special
background="#11000a"
foreground="#f0ae9c"
cursor="#f0ae9c"

-- Colors
color0="#11000a"
color1="#EA1E1B"
color2="#F52F1B"
color3="#D51B23"
color4="#DC1F20"
color5="#FF481C"
color6="#FB5E25"
color7="#f0ae9c"
color8="#a8796d"
color9="#EA1E1B"
color10="#F52F1B"
color11="#D51B23"
color12="#DC1F20"
color13="#FF481C"
color14="#FB5E25"
color15="#f0ae9c"
