# Shell variables
# Generated by 'wal'
wallpaper='/home/baphomet/Pictures/wallpaper.jpg'

# Special
background='#11000a'
foreground='#f0ae9c'
cursor='#f0ae9c'

# Colors
color0='#11000a'
color1='#EA1E1B'
color2='#F52F1B'
color3='#D51B23'
color4='#DC1F20'
color5='#FF481C'
color6='#FB5E25'
color7='#f0ae9c'
color8='#a8796d'
color9='#EA1E1B'
color10='#F52F1B'
color11='#D51B23'
color12='#DC1F20'
color13='#FF481C'
color14='#FB5E25'
color15='#f0ae9c'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
