--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/baphomet/Pictures/wallpaper21.jpg"

-- Special
background="#252544"
foreground="#d7acb7"
cursor="#d7acb7"

-- Colors
color0="#252544"
color1="#CB6874"
color2="#715B85"
color3="#745A84"
color4="#895B81"
color5="#8E678A"
color6="#AB6884"
color7="#d7acb7"
color8="#967880"
color9="#CB6874"
color10="#715B85"
color11="#745A84"
color12="#895B81"
color13="#8E678A"
color14="#AB6884"
color15="#d7acb7"
