# Shell variables
# Generated by 'wal'
wallpaper='/home/baphomet/Pictures/wallpaper21.jpg'

# Special
background='#252544'
foreground='#d7acb7'
cursor='#d7acb7'

# Colors
color0='#252544'
color1='#CB6874'
color2='#715B85'
color3='#745A84'
color4='#895B81'
color5='#8E678A'
color6='#AB6884'
color7='#d7acb7'
color8='#967880'
color9='#CB6874'
color10='#715B85'
color11='#745A84'
color12='#895B81'
color13='#8E678A'
color14='#AB6884'
color15='#d7acb7'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
